In [1]:
# Import packages
import copy
import numpy as np
import random

In [ ]:
# Global variables: the size of the board
row_count = 6
col_count = 7

In [ ]:
def drawBoard(board):
    # Board is a 6 * 7 numpy array
    # Reverse the array vertically so that the piece always goes to the bottom of board first
    print(np.flip(board, 0))

In [2]:
def inputPlayerNumber():
    number = 0
    # Since I use numpy array to store the board, I use 1 as the substitute of the letter "X", 2 as the substitute of "O"
    while not (number == 1 or number ==2):
        print('Do you want to be 1 or 2?')
        number = int(input())
        
    # The first number is the player' number, the second is the computer's number
    if number ==1:
        return [1, 2]
    else:
        return [2, 1]

In [3]:
def whoGoesFirst():
    # Randomly choose the player who goes first, 0 means computer going first
    if random.randint(0,1) == 0:
        return 'computer'
    else:
        return 'player'

In [4]:
def playAgain():
    print('Do you want to play again? (yes or no)')
    return input().lower().startswith('y')

In [5]:
def makeMove(board, number, move):
    col_position = 0
    for col_position in range(row_count):
        if  board[col_position][move] == 0:
            board[col_position][move] = number
            break

In [6]:
def isWinner(bo, le):
    # Check horizontally
    for c in range(col_count - 3):
        for r in range(row_count):
            if bo[r][c] == le and bo[r][c+1] == le and bo[r][c+2] == le and bo[r][c+3] == le:
                return True
    # Check vertically
    for c in range(col_count):
        for r in range(row_count - 3):
             if bo[r][c] == le and bo[r+1][c] == le and bo[r+2][c] == le and bo[r+3][c] == le:
                return True
    # Check positive  diagonal
    for c in range(col_count - 3):
        for r in range(row_count - 3):
            if bo[r][c] == le and bo[r+1][c+1] == le and bo[r+2][c+2] == le and bo[r+3][c+3] == le:
                return True
    # Check negative diagonal:
    for c in range(col_count - 3):
        for r in range(3, row_count):
            if bo[r][c] == le and bo[r-1][c+1] == le and bo[r-2][c+2] == le and bo[r-3][c+3] == le:
                return True

In [7]:
def getBoardCopy(board):
    # Make a duplicate of the board list and return it the duplicate. 
    dupeBoard = copy.deepcopy(board)
    return dupeBoard

In [8]:
def isSpaceFree(board, move):
    # I exclusively check the top row because if the top is not filled then there is space free
    return board[5][move] == 0

In [9]:
def getPlayerMove(board):
    # Let the player type in their move. 
    move = 7
    while move not in [0,1,2,3,4,5,6] or not isSpaceFree(board, int(move)):
        print('What is your next move? (0-6)')
        move = int(input())
    return int(move)

In [10]:
def chooseRandomMoveFromList(board, moveList):
    # Returns a valid move from the passed list on the passed board.
    # Returns None if there is no valid move.
    possibleMoves = []          
    for i in moveList:
        if isSpaceFree(board, i):
             possibleMoves.append(i)  

    if len(possibleMoves) != 0:     
        return random.choice(possibleMoves)
    else:
        return None

In [11]:
def getComputerMove(board, computerNumber): 
    # Given a board and the computer's letter, determine where to move and return that move.
    if computerNumber == 1:
        playerNumber = 2
    else:
        playerNumber = 1

    # First, check if we can win in the next move 
    for i in range(7):
        copy = getBoardCopy(board)    
        if isSpaceFree(copy, i):
            makeMove(copy, computerNumber, i)
            if isWinner(copy, computerNumber):
                return i              

    # Check if the player could win on their next move, and block them. 
    for i in range(7):
        copy = getBoardCopy(board)
        if isSpaceFree(copy, i):
            makeMove(copy, playerNumber, i)
            if isWinner(copy, playerNumber):
                return i 
    # For simplicity, let computer choose a random colomn to drop the number       
    return chooseRandomMoveFromList(board,[0,1,2,3,4,5,6])



In [12]:
def isBoardFull(board):
    # Return True if every space on the board has been taken. Otherwise return False.
    for col in range(col_count):
        if isSpaceFree(board, col):
            return False
    return True

In [ ]:
print('Welcome to Tic Tac Toe!')
# The algorithm for Connect Four
while True: 
    
    theBoard = np.zeros((6,7)) 
    print(theBoard)
    
    playerNumber, computerNumber = inputPlayerNumber()   
    turn = whoGoesFirst()         
    print('The ' + turn + ' will go first.')
    gameIsPalying = True  
    
    while gameIsPalying:        
        if turn == 'player':                 
            drawBoard(theBoard)              
            move = getPlayerMove(theBoard)   
            makeMove(theBoard, playerNumber, move) 

            if isWinner(theBoard, playerNumber):
                drawBoard(theBoard)
                print('Hooray! You have won the game!')
                gameIsPalying = False
            else:
                if isBoardFull(theBoard):        
                    drawBoard(theBoard)
                    print('The game is a tie!')
                    break
                else:
                    turn = 'computer'            

        else:
            move = getComputerMove(theBoard, computerNumber) 
            makeMove(theBoard, computerNumber, move)        

            if isWinner(theBoard, computerNumber):           
                drawBoard(theBoard)
                print('The computer has beaten you! You lose.')
                gameIsPalying = False
            else:
                if isBoardFull(theBoard):
                    drawBoard(theBoard)
                    print('The game is a tie!')
                    break
                else:
                    turn = 'player'                        

    if not playAgain():
        break              

Welcome to Tic Tac Toe!
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Do you want to be 1 or 2?
1
The computer will go first.
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2.]]
What is your next move? (0-6)
1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 2. 2.]]
What is your next move? (0-6)
4
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 2. 2.]]
What is your next move? (0-6)
2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0.]
 [0. 1. 1. 2. 1. 2. 2.]]
What is your next move? (0-6)
2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.